# Generated by Django 2.0.6 on 2018-06-22 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, verbose_name='address')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is_verified')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is_primary')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'emails',
                'verbose_name': 'email',
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent', models.DateTimeField(null=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Email')),
            ],
            options={
                'verbose_name_plural': 'email confirmations',
                'verbose_name': 'email confirmation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('user', 'address')},
        ),
    ]
